
#define LOG_CONF_LEVEL_RPL LOG_LEVEL_WARN
// #define LOG_CONF_LEVEL_MAC LOG_LEVEL_DBG

#define LOG_CONF_WITH_ANNOTATE 1

// #define RPL_CONF_WITH_STORING           0
// #define RPL_CONF_WITH_NON_STORING       0
// #define RPL_CONF_MOP RPL_MOP_NO_DOWNWARD_ROUTES

#define SEND_INTERVAL (unsigned long) (CLOCK_SECOND / 0.1)

#define OFF_TIMER_THRESHOLD 3
#define OFF_TIMER_TIME SEND_INTERVAL*2

#define RPL_CONF_OF_OCP RPL_OCP_OF0